package com.siniswift.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-04-02T15:12:50.074+08:00
 * Generated source version: 3.2.4
 *
 */
@WebServiceClient(name = "SyncWebServiceImplService",
                  wsdlLocation = "http://localhost:8090/ws/sync?wsdl",
                  targetNamespace = "http://impl.webservice.siniswift.com/")
public class SyncWebServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.webservice.siniswift.com/", "SyncWebServiceImplService");
    public final static QName SyncWebServiceImplPort = new QName("http://impl.webservice.siniswift.com/", "SyncWebServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8090/ws/sync?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SyncWebServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8090/ws/sync?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SyncWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SyncWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SyncWebServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public SyncWebServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SyncWebServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SyncWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns SyncWebService
     */
    @WebEndpoint(name = "SyncWebServiceImplPort")
    public SyncWebService getSyncWebServiceImplPort() {
        return super.getPort(SyncWebServiceImplPort, SyncWebService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SyncWebService
     */
    @WebEndpoint(name = "SyncWebServiceImplPort")
    public SyncWebService getSyncWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(SyncWebServiceImplPort, SyncWebService.class, features);
    }

}
